# Generated by Django 2.2.7 on 2019-11-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('Emailid', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(default=None, max_length=120)),
                ('confirmpassword', models.CharField(default=None, max_length=120)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
